GET http":"//localhost:4000/api/user/16
###
GET http://localhost:4000/api/wakprint/1
###
GET http://localhost:4000/api/wakprint/4
###
GET http://localhost:4000/api/toko/search?s=tes
###
POST http://localhost:4000/api/user/register
Content-Type: application/json
{
    "email_user":"hello1",
    "password_user":"helloa1",
    "nama_lengkap_user":"hello",
    "nomor_hp_user":"hello",
    "alamat_user":"hello"
}
###
POST http://localhost:4000/api/user/login
Content-Type: application/json

{
    "email_user":"hello1",
    "password_user":"helloa1"
}
###
POST http://localhost:4000/api/partner/register
Content-Type: application/json

{
    "email":"hello@gmail.com",
    "password":"hello123",
    "full_name":"hello",
    "business_name":"hello",
    "phone_number":"hello",
    "address":"hello",
    "description":"hello"
}
###
POST http://localhost:4000/api/partner/login
Content-Type: application/json

{
    "email":"hello@gmail.com",
    "password":"hello123"
}