POST http://localhost:4000/api/user/register
Content-Type: application/json

{
    "email":"ibrahimtarigan1@gmail.com",
    "password":"test123",
    "fullName":"ibrahim tarigan",
    "phoneNumber":"081260086777",
    "address":"Jln. Jend Jamin Ginting No.273, Padang Bulan, Medan"
}
###
POST http://localhost:4000/api/user/login
Content-Type: application/json

{
    "email":"ibrahimtarigan1@gmail.com",
    "password":"test123"
}
###
GET http://localhost:4000/api/user/4
###
PUT http://localhost:4000/api/user/4
Content-Type: application/json

{
    "fullName":"ibrahim trg1",
    "phoneNumber":"0812345678901",
    "address":"Medan"
}
###
GET http://localhost:4000/api/user/4/photo
###
PATCH http://localhost:4000/api/user/4/photo
Content-Type: multipart/form-data

{
    "photo":"D:\\266509"
}
###
POST http://localhost:4000/api/partner/register
Content-Type: application/json

{
    "email":"ibrahimtarigan@gmail.com",
    "password":"test123",
    "fullName":"ibrahim tarigan",
    "businessName":"print trg",
    "phoneNumber":"081260086777",
    "address":"Jln. Jend Jamin Ginting No.273, Padang Bulan, Medan"
}
###
POST http://localhost:4000/api/partner/login
Content-Type: application/json

{
    "email":"ibrahimtarigan@gmail.com",
    "password":"test123"
}
###
GET http://localhost:4000/api/partner/9
###
PUT http://localhost:4000/api/partner/9
Content-Type: application/json

{
    "fullName":"ibrahim trg",
    "businessName":"sinar print",
    "phoneNumber":"081234567890",
    "address":"Medan"
}
###
GET http://localhost:4000/api/partner/9/photo
###
PATCH http://localhost:4000/api/partner/9/photo
###
GET http://localhost:4000/api/partner/17/orders
###
GET http://localhost:4000/api/search?s=
###
POST http://localhost:4000/api/order
###
GET http://localhost:4000/api/order/21
###
PATCH http://localhost:4000/api/order/27/confirm
###
PATCH http://localhost:4000/api/order/21/decline
###
PATCH http://localhost:4000/api/order/21/done
###
GET http://localhost:4000/api/order/1/download
###
POST http://localhost:4000/api/balance/deposit
Content-Type:  application/json

{
    "userId": 1,
    "nominal": 20000
}
###
POST http://localhost:4000/api/balance/withdraw
Content-Type:  application/json

{
    "partnerId": 1,
    "nominal": 20000,
    "bankNumber": "55310828340293"
}
###
DELETE http://localhost:3000/api/partner/17/product/4